-- use schema DEMO_DB.DEVOPS;
-- V has to be UPPER CASE to work with SchamaChange

CREATE OR REPLACE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
  SYNTAX ERROR LOL
  -- ,MIDDLE_INITITAL VARCHAR
);